
import { ChakraProvider, Icon } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { BiSolidHeart, BiFilter } from "react-icons/bi";
import { useDisclosure } from "@chakra-ui/react";

const inter = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

interface RootLayoutProps {
  children: React.ReactNode;
  onOpenAddToFavorites: () => void;
  handleOpenFilterModal: () => void;
}

export const metadata: Metadata = {
  title: "TaskNext",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  onOpenAddToFavorites,
  handleOpenFilterModal,
}: RootLayoutProps) {
  return (
    <html className={inter.className}>
      <body className="bg-blue-300 bg-cover bg-no-repeat">
        <main>{children}</main>
      </body>
    </html>
  );
}
